[package]
name = "deep_core"
version = "0.1.1"
authors = ["tglanz"]
description = "deep prototype"
repository = "https://github.com/tglanz/deep"
readme = "readme.md"
license-file = "license"

[dependencies]